### ISSUE TITLE
o.c.ui.util 4.0.2?

### ISSUE THREAD

**Issue by berryma4** [frib-high-level-controls/save-set-restore#1]
https://github.com/frib-high-level-controls/save-set-restore/blob/master/plugins/org.csstudio.saverestore.git/META-INF/MANIFEST.MF#L26

The cs-studio repo has 4.0.0.  Do you have changes for cs-studio?

**Comment by berryma4** [comment]
fot now, I changed it back to 4.0.0:
https://github.com/frib-high-level-controls/save-set-restore/commit/50411685722e95d45110da915b425770e17858c9

**Comment by berryma4** [comment]
@jbobnar

**Comment by jbobnar** [comment]
Sorry for that. I was using ITER's master branch for the css sources and we have a few updates for that plugin. 4.0.0 should be fine. I only need it for some preferences stuff.
