### ISSUE TITLE
save snapshot takes a few clicks

### ISSUE THREAD

**Issue by berryma4** [frib-high-level-controls/save-set-restore#10]
It seems to take a few clicks to get a snapshot:
![image](https://cloud.githubusercontent.com/assets/854021/12891192/d7166a84-ce54-11e5-9a9d-f8efc47adecc.png)

I few clicks later:

![image](https://cloud.githubusercontent.com/assets/854021/12891235/ffd4a54e-ce54-11e5-99fe-1c16dc341232.png)

**Comment by jbobnar** [comment]
Not sure if I understand the problem. Are you talking about all those live PVs without values? In that case, can you check the date of your features/plugins, because I know I had this problem, but I fixed it last end of last week (Thursday or Friday).

**Comment by jbobnar** [comment]
Never mind. I managed to reproduce this.

**Comment by jbobnar** [comment]
It should be fixed: 7854b35

**Comment by berryma4** [comment]
Yes!  Thank you!
