### ISSUE TITLE
Disable Save-Set-Restore

### ISSUE THREAD

**Issue by dylan171** [frib-high-level-controls/save-set-restore#11]
I am trying to disable save-set-restore, so I set the 'plugin_customizatio.ini' file as follows:

#org.csstudio.saverestore.git/url=https://stash.nscl.msu.edu/scm/saveset/test.git
#org.csstudio.saverestore.git/destination=
#org.csstudio.saverestore.git/automaticSynhronisation=true

But for some reason I can still access the data in CS Studio.

Also, can I use a local repository instead of HTTP?

Dylan

**Comment by berryma4** [comment]
disable, as in remove?  If you comment out the 'plugin_customizatio.ini', then the defaults in the plugin will be used.

**Comment by berryma4** [comment]
But, yes a local repository instead of HTTP would be nice ... is this already possible, as in we need to know the uri format?

**Comment by dylan171** [comment]
When I setup CS Studio to run in the isolated VM, I try to disable external services, like the archiver, olog, etc.  For these other service I simply removed there configuration so they couldn't connect to the outside service, that seemed good enough, I don't think I need to remove the olog plugin or the archiver plugin, etc.  Ultimately I would prefer to have a local GIT repo for save-set-restore.

**Comment by jbobnar** [comment]
Yes, that is possible and is coming your way (tomorrow), I just need to do a bit more testing. You will be able to specify the path to a folder on the local file system and it will be treated as a git repository, or a repository will be created, if the destination is empty.
No push/pull will ever be performed on such repository. That actually makes it a much faster service, but you'll have to find a way to merge the local repository with the central repo manually (if needed).

Removing the setting in the plugin_customization.ini default to my test repo. I'll remove that.

**Comment by jbobnar** [comment]
This should work now.
