### ISSUE TITLE
cannot copy pv name from a data set

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#15]
Cannot copy pv name to clip-board, it reports that "PV name is empty! Nothing will be copied".
But sending the same pv name to data browser works properly.

**Comment by shengb** [comment]
also pv probe cannot get right pv name

**Comment by berryma4** [comment]
This has a fix as a pull request, we just haven't agreed on the
implementation.

**Comment by berryma4** [comment]
I should have mentioned, the fix is in CS-Studio.

**Comment by shengb** [comment]
Do I need a new CS-Studio for that?

**Comment by berryma4** [comment]
Yes, when we come up with a decent solution.
https://github.com/ControlSystemStudio/cs-studio/pull/1560

**Comment by berryma4** [comment]
closing thins, because it is a repeat:
https://github.com/frib-high-level-controls/save-set-restore/issues/9
