### ISSUE TITLE
"Take Snapshot" button 

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#17]
The "Take Snapshot" button only appears after I retrieved a saved data set.
If there is no pre-saved set, I can not take a snapshot for a given beamline.

**Comment by jbobnar** [comment]
There is an Open button, which will open a blank editor and you can take snapshot.

![capture](https://cloud.githubusercontent.com/assets/5602519/13139767/72dc0d12-d62e-11e5-9e79-44818f675c58.PNG)

Now that you mentioned, how do you that with the python client?

**Comment by shengb** [comment]
The way I am doing in Python is I allow use to click on save snapshot once a configuration, which is Beamline Sets in this UI, is selected.

**Comment by shengb** [comment]
Is there any instruction how to take a snapshot?
After I clicked "Take Snapshot", nothing happened. I cannot see the snapshot anywhere, and cannot save it.
![screen shot 2016-02-18 at 6 15 55 pm](https://cloud.githubusercontent.com/assets/3741779/13161472/ec8f0e60-d66b-11e5-925a-3ca86f252985.png)

**Comment by jbobnar** [comment]
Help is available in the Help -> Help Contents, or by pressing the F1 key.

When you created the above screenshot, did you really press the Take Snapshot button? Based on what I see, I think you pressed the "Open" button. Pressing the open button will not take a new snapshot, it will obtain the list of PVs from the data provider and create a blank snapshot (I have to deal with the DISCONNECTED values). 

Unfortunately, in the masar case there is no direct way of obtaining the list of pv names in the set, so a snapshot has to be fetched. If there is an existing snapshot for that set, it is loaded; if there is no snapshot available a new one is created, but immediately thrown away - only the pv names are kept.

**Comment by shengb** [comment]
Yes, I did click the take snapshot button. @berryma4 also tried it, but there is no new window.
Actually, the data saved into database, just the client did not show it.

**Comment by jbobnar** [comment]
I tried to reproduce this, but couldn't. 
I suspect it to be the same connection issue as mentioned in other tickets (#12 and #18). The time when you observed this issue is about right. The latest release should no longer have it. If you see it, let me know and we'll take it from there.
