### ISSUE TITLE
Export contents to file (.csv): Del format

### ISSUE THREAD

**Issue by crispd** [frib-high-level-controls/save-set-restore#20]
![arssr](https://cloud.githubusercontent.com/assets/7905813/13261275/5aceb320-da2d-11e5-8539-e5145e03e9a4.JPG)
Is there something we can do about the delta here? We may not need the delta in a spreadsheet, thoughts?

**Comment by crispd** [comment]
The delta value may still be nice to have.. my point is a raw data column would be most convenient. Whether the delta values go into a separate column or something else is of less importance.

**Comment by jbobnar** [comment]
I removed the delta from the output.

**Comment by crispd** [comment]
great, thanks.
