### ISSUE TITLE
details for not restored PV list

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#23]
when trying to restore a snapshot, if there is any PV not restored, it will report an restore error.
it would be better to show the list of PVs not restored for further investigation.

**Comment by jbobnar** [comment]
There is a details button on the dialog, which shows exactly that.
![restoreerror](https://cloud.githubusercontent.com/assets/5602519/13805143/e6d93990-eb52-11e5-983a-8a5d7e00fa38.png)

The same information is also printed to the CSS console.

**Comment by shengb** [comment]
Yes, there are there. Thanks.
