### ISSUE TITLE
Color coding

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#25]
Got some color on stored Setpoint.
Is there a document to explain what the color mean?
![screen shot 2016-03-15 at 5 24 04 pm](https://cloud.githubusercontent.com/assets/3741779/13794605/1e63c6e4-ead3-11e5-9228-d4c6742e4638.png)

**Comment by jbobnar** [comment]
In this case, it is a bug. I missed the case when the values are string types. When string values were compared, the result was always "they are different". It's been fixed: 8809b60

In general red color with exclamation mark means that values are different. If the values are numbers, they are compared as numbers. An "ai" value of 0.0 is equal to "longin" 0. If the values are of different types (enum vs int, or int vs string) they are always treated as different. Disconnected values are also red, but the icon is different (the red circle with an X). I added this info to help as well.

**Comment by shengb** [comment]
In the example, the for masarExample0003, which is "one", still shows as red.

**Comment by jbobnar** [comment]
Can you upload your IOC code somewhere, so that I can test on the same setup that you are using? 
Thanks!

**Comment by shengb** [comment]
the db file are is under masarService/test/v3IOC.
Here is my way to start the IOC:
1. $ cd masarService/test/v3IOC
2. $ softIoc st.cmd

**Comment by jbobnar** [comment]
This is masar bug. It doesn't save the enum values correctly. There are also problem with other types.

When I press "Take Snapshot" button, this is the answer I get from masar:

```
epics:nt/NTMultiChannel:1.0 
    any[] value 
        any 
            byte[]  [0,0,0,0,0,0,0,0,0,0]
        any 
            enum_t 
                int index 1
                string[] choices [zero,one,two,three,four,five,six,seven,eight,nine,ten,eleven,twelve,thirteen,fourteen,fifteen]
    string[] channelName [TEST3,masarExample0003]
    string descriptor 
    alarm_t alarm
        int severity 2
        int status 7
        string message Machine preview Successed.
    time_t timeStamp
        long secondsPastEpoch 1458251918
        int nanoseconds 784096373
        int userTag 37
    int[] severity [3,3]
    int[] status [3,3]
    string[] message [UDF_ALARM,UDF_ALARM]
    long[] secondsPastEpoch [631152000,631152000]
    int[] nanoseconds [0,0]
    int[] userTag [0,0]
    boolean[] isConnected [true,true]
    int[] dbrType [4,0]
```
All is fine, except that the dbrType for masarExample0003 should be 3 (DBR_ENUM) and not 0 (DBR_STRING).

Then I press "Save Button", wait for the snapshot to save, close all editors and open the recently saved snapshot. Masar returns this:
```
epics:nt/NTMultiChannel:1.0 
    any[] value 
        any 
            int[]  [0,0,0,0,0,0,0,0,0,0]
        any 
            string  one
    string[] channelName [TEST3,masarExample0003]
    alarm_t alarm
        int severity 0
        int status 0
        string message 
    time_t timeStamp
        long secondsPastEpoch 0
        int nanoseconds 0
        int userTag 0
    int[] severity [3,3]
    int[] status [3,3]
    string[] message [UDF_ALARM,UDF_ALARM]
    long[] secondsPastEpoch [631152000,631152000]
    int[] nanoseconds [0,0]
    int[] userTag [0,0]
    boolean[] isConnected [true,true]
    int[] dbrType [4,0]
```
As you can see the enum value became a string value. 
In addition the byte array value of TEST3 became an int array value.

**Comment by shengb** [comment]
Thanks. The data mapping is because of the design instead of a bug 
which was driven by the Python object.
here is a mapping:
epics data type => data type carried by MASAR
enum, string => string
byte, short, int/long => long
float, double => double

we can close it for now and I will think about the solution again.
