### ISSUE TITLE
Secondary Beamline Sets

### ISSUE THREAD

**Issue by crispd** [frib-high-level-controls/save-set-restore#5]
I see that this was addressed by allowing for a second tier in the 'Beamline Sets for *' area. The idea is to allow for subsections to be quickly handled by save/restore functions, but my comment is that it's more likely that the subset a user wants/needs is not foreseeable. Meaning I think it'd be very useful to be able to query on pv's for restore or compare from the snapshot view itself. One could quickly choose the RF devices in just one cryomodule for viewing/restoring instead of being limited to either search and check, or being required to have had the foresight of making a beamline 'subset' beforehand. (ability to query within snapshot view may also deter overzealous creations of beamline 'subsets' for every possible scenario)

**Comment by berryma4** [comment]
@crispd I believe the filter fits these needs.

**Comment by crispd** [comment]
Yes, the filter seems to fit these needs well. Thank you!
