### ISSUE TITLE
Comparison Delta Discussion

### ISSUE THREAD

**Issue by crispd** [frib-high-level-controls/save-set-restore#7]
We spoke in the meeting yesterday about helping the eye more easily identify what I'm calling a comparison delta (the difference between two set values in a compare).

I'm starting this issue thread to take on the topic.

It was mentioned that we currently have some apps/features which do a set value compare where the column showing any 'comparison delta' appears empty for all rows where the 'comparison delta' is not outside some tolerance. (or is otherwise zero)

If we had to define what tolerances are for displaying a given 'comparison delta', outside of using something like channelfinder to serve independent tolerences, I'd just as well assume defining one tolerance per device type. Quads/Dipoles/Correctors/Cavities
Here's an example of a quadrupole record name: REA_BTS30:PSQ_D1221:I_CSET
The device portion of a quadrupole device or supply could be: PSQ|Q|PSQ1|PSQ2|PSQ3|PSQ4

Thoughts?

**Comment by berryma4** [comment]
@crispd, the delta is added to the file.  This should solve the issue?

**Comment by crispd** [comment]
The comparison delta is there...  and I like that the files includes a csv delta column, I suppose we could script some initial delta values we think are appropriate and let device experts (area owners) define unique deltas to their devices as needed. Let me know if I'm misguided in thinking this, but I'm closing the issue.
