### ISSUE TITLE
git login popup

### ISSUE THREAD

**Issue by berryma4** [frib-high-level-controls/save-set-restore#8]
When cs-studio starts up, the git login immediately pops up.

Can we:
  - only pop up if the remote git it's blank (allowing only local git)
  - pop up only when the save restore application is selected

It would be neat to do something token based instead.  Or maybe ssh keys ... through jgit?

**Comment by jbobnar** [comment]
The login pops up only when the save restore application is selected. I haven't figured out yet how to do ssh.

**Comment by berryma4** [comment]
I think the ssh keys are up to us (this is a git issue, not the application)
